language: node_js
node_js: stable


cache:
  directories:
  - node_modules
install:
- npm install
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy