language: node_js
node_js: stable

# safelist
branches:
  only:
  - hexo_version

cache:
  directories:
  - node_modules
install:
- npm install
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo generate
after_success:
- git config user.name "alice"
- git config user.email "alice"
- sed -i "s/mytoken/${mytoken}/g" ./_config.yml
- hexo deploy