name: CI

run-name: [alice's workflow run] ${{ github.actor }} 

on:
  push:
    branches:
      - hexo_version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@hexo_version

      - name: Setup Node
        uses: actions/setup-node@hexo_version
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install
          npm install hexo-deployer-git --save
          npm install -g hexo-cli
          npm run build
          npm --version
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public



