# This is a basic workflow to help you get started with Actions
name: CI

# optional
run-name: [alice's workflow run] ${{ github.actor }} 

on:
  push:
    branches:
      - hexo_version

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@hexo_version

      - name: Setup Node
        uses: actions/setup-node@hexo_version
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install
          npm install hexo-deployer-git --save
          npm install -g hexo-cli
          npm run build
          npm --version
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public



